### ISSUE TITLE
[Feature Request] Float64 support

### ISSUE THREAD

**Issue by sukirk** [gngdb/pytorch-minimize#2]
* PyTorch Minimize version: 1.9.0
* Python version: 3.8
* Operating System: Windows

### Description

I try to use this package for numerical calculations with float32 or float64. 
I tried lots of optimizers, and the BFGS perform well in my code.

I notice that in optim.py, the data always convert to float32 before the calculation of the closure function regardless of whatever I input, then this data convert to float64 finally.
When I use float32, my code behaves as expected.
But when I tried to use float64 in the closure function, the code produced the wrong result.

I tried to modify optim.py so that the closure function can be compatible with float32 and float64, but I failed.
 I would really appreciate any help.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by gngdb** [comment]
I've added a branch to support this: https://github.com/gngdb/pytorch-minimize/tree/floatX

If the parameters supplied are double precision it will cast to double precision internally, otherwise it'll cast to float. I added it to the tests and it passes. Let me know if it works for what you're trying to do. If you're not using a dev install you can install specific branches from git repos with pip [like this](https://stackoverflow.com/a/20101940/6937913).

**Comment by sukirk** [comment]
@gngdb Thanks, it works for me.
